### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Dan-Mqs** [ysndmr/SylUI-Header#1]
Hello there!

I liked the design and the idea of your kit, it really looks nice and modern, and very simple to use.

However, I've found some issues you might want to have a look into. I'm on mobile, iPhone 7, Safari.

- The divs/sections are not centered in my browser;
- The content in these divs/sections don't fit in the containers;
- The images within the divs/sections are vertically stretched.

![image](https://user-images.githubusercontent.com/76232545/103486767-fa28fa00-4dde-11eb-9259-ee5aeaeef47b.jpeg)

I'm really not experienced nor have enough knowledge to suggest you a fix for these issues, but I really do hope this feedback may help you in some way. **Keep up the good work!**

**Comment by ysndmr** [comment]
Hi Dan-Mqs, first of all I would like to say thank you for your feedback. You was right and I think I fix it. Thanks for your sharing.

**Comment by Dan-Mqs** [comment]
Glad I could help! 
Best of luck.
